spring.application.name=route-planner
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/delhi_metro_db
spring.datasource.username=postgres
spring.datasource.password=rootadmin321
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

logging.level.com.delhimetro=DEBUG
logging.level.org.springframework.web=INFO